num_classes: 22  # include background
img_size: 256
batch_size: 4
num_epochs: 2

loss:
  # name: ComboLoss
  # params:
  #   num_classes: 5
  #   ignore_index: null
  #   weights:
  #     - 0.5
  #     - 0.5
  # name: FocalLoss
  # params:
  #   gamma: 2.0
  #   size_average: True
  name: CrossEntropyLoss
  params:
    weight: null
    size_average: null
    ignore_index: -100
    reduce: null
    reduction: mean
optimizer:
  name: SGD
  params:
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0003
scheduler:
  # name: CosineAnnealingLR
  # params:
    # T_max: 3
    # eta_min: 0.0001
    # last_epoch: -1
  name: CosineAnnealingWarmRestarts
  params:
    T_0: 10
    T_mult: 2
    eta_min: 0.0001
    last_epoch: -1
model:
  architecture: unet  # fpn of unet
  backbone: resnet18
albumentations:
  eval:
    __version__: 0.4.6
    transform:
      __class_fullname__: albumentations.core.composition.Compose
      p: 1.0
      transforms:
      - __class_fullname__: albumentations.augmentations.transforms.Normalize
        always_apply: False
        max_pixel_value: 255.0
        mean:
        - 0.485
        - 0.456
        - 0.406
        p: 1.0
        std:
        - 0.229
        - 0.224
        - 0.225
      - __class_fullname__: albumentations.augmentations.transforms.Resize
        height: 256
        width: 256
        interpolation: 1
        always_apply: false
        p: 1
  train:
    __version__: 0.4.6
    transform:
      __class_fullname__: albumentations.core.composition.Compose
      p: 1.0
      transforms:
      - __class_fullname__: albumentations.augmentations.transforms.Normalize
        always_apply: false
        max_pixel_value: 255.0
        mean:
        - 0.485
        - 0.456
        - 0.406
        p: 1.0
        std:
        - 0.229
        - 0.224
        - 0.225
      - __class_fullname__: albumentations.augmentations.transforms.GaussNoise
        always_apply: false
        p: 0.5
        var_limit:
        - 10.0
        - 50.0
        mean: 0
      - __class_fullname__: albumentations.augmentations.transforms.VerticalFlip
        always_apply: false
        p: 0.5
      - __class_fullname__: albumentations.augmentations.transforms.Resize
        height: 256
        width: 256
        interpolation: 1
        always_apply: false
        p: 1
