num_classes: 22  # include background
img_size: 256
batch_size: 4
num_epochs: 2

loss:
  # name: ComboLoss
  # params:
  #   num_classes: 5
  #   ignore_index: null
  #   weights:
  #     - 0.5
  #     - 0.5
  # name: FocalLoss
  # params:
  #   gamma: 2.0
  #   size_average: True
  name: CrossEntropyLoss
  params:
    weight: null
    size_average: null
    ignore_index: -100
    reduce: null
    reduction: mean
optimizer:
  name: SGD
  params:
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0003
scheduler:
  # name: CosineAnnealingLR
  # params:
    # T_max: 3
    # eta_min: 0.0001
    # last_epoch: -1
  name: CosineAnnealingWarmRestarts
  params:
    T_0: 10
    T_mult: 2
    eta_min: 0.0001
    last_epoch: -1
model:
  architecture: unet  # fpn of unet
  backbone: resnet18