# Constant variables
num_classes: 22  # include background

# Hyper parameters
backbone: resnet18  # null or ResNet backbone.
img_size: 256
batch_size: 4
num_epochs: 2
min_lr: 0.00005
max_lr: 0.01
momentum: 0.9
weight_decay: 0.0003
