num_classes: 22  # include background

# Hyper parameters
img_size: 256
batch_size: 4
num_epochs: 2
min_lr: 0.00005
max_lr: 0.01
momentum: 0.9
weight_decay: 0.0003

optimizer:
  name: SGD
  params:
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0003
scheduler:
  # name: CosineAnnealingLR
  # params:
    # T_max: 3
    # eta_min: 0.0001
    # last_epoch: -1
  name: CosineAnnealingWarmRestarts
  params:
    T_0: 10
    T_mult: 2
    eta_min: 0.0001
    last_epoch: -1
model:
  architecture: unet  # fpn of unet
  backbone: resnet18